#pragma once
#include "token.h"
#include <iostream>
const char* token_kind_name(TokenKind kind) {
	switch (kind) {
	case TokenKind::KW_FN:
		return "KW_FN";
	case TokenKind::KW_LET:
		return "KW_LET";
	case TokenKind::KW_IF:
		return "KW_IF";
	case TokenKind::KW_ELSE:
		return "KW_ELSE";
	case TokenKind::KW_WHILE:
		return "KW_WHILE";
	case TokenKind::KW_FOR:
		return "KW_FOR";
	case TokenKind::KW_RETURN:
		return "KW_RETURN";
	case TokenKind::KW_STRUCT:
		return "KW_STRUCT";
	case TokenKind::KW_MUT:
		return "KW_MUT";
	case TokenKind::KW_IN:
		return "KW_IN";
	case TokenKind::KW_BREAK:
		return "KW_BREAK";
	case TokenKind::KW_CONTINUE:
		return "KW_CONTINUE";
	case TokenKind::KW_VOID:
		return "KW_VOID";
	case TokenKind::KW_BOOL:
		return "KW_BOOL";
	case TokenKind::KW_CHAR:
		return "KW_CHAR";
	case TokenKind::KW_I32:
		return "KW_I32";
	case TokenKind::KW_U32:
		return "KW_U32";
	case TokenKind::KW_USIZE:
		return "KW_USIZE";
	case TokenKind::KW_F32:
		return "KW_F32";
	case TokenKind::KW_F64:
		return "KW_F64";
	case TokenKind::KW_STRING:
		return "KW_STRING";
	case TokenKind::OP_PLUS:
		return "OP_PLUS";
	case TokenKind::OP_MINUS:
		return "OP_MINUS";
	case TokenKind::OP_MULTIPLY:
		return "OP_MULTIPLY";
	case TokenKind::OP_DIVIDE:
		return "OP_DIVIDE";
	case TokenKind::OP_ASSIGN:
		return "OP_ASSIGN";
	case TokenKind::OP_EQUAL:
		return "OP_EQUAL";
	case TokenKind::OP_NOT_EQUAL:
		return "OP_NOT_EQUAL";
	case TokenKind::OP_LESS:
		return "OP_LESS";
	case TokenKind::OP_GREATER:
		return "OP_GREATER";
	case TokenKind::OP_LESS_EQUAL:
		return "OP_LESS_EQUAL";
	case TokenKind::OP_GREATER_EQUAL:
		return "OP_GREATER_EQUAL";
	case TokenKind::OP_LOGICAL_AND:
		return "OP_LOGICAL_AND";
	case TokenKind::OP_LOGICAL_OR:
		return "OP_LOGICAL_OR";
	case TokenKind::OP_LOGICAL_NOT:
		return "OP_LOGICAL_NOT";
	case TokenKind::OP_BITWISE_AND:
		return "OP_BITWISE_AND";
	case TokenKind::OP_BITWISE_OR:
		return "OP_BITWISE_OR";
	case TokenKind::OP_BITWISE_XOR:
		return "OP_BITWISE_XOR";
	case TokenKind::OP_BITWISE_NOT:
		return "OP_BITWISE_NOT";
	case TokenKind::OP_LEFT_SHIFT:
		return "OP_LEFT_SHIFT";
	case TokenKind::OP_RIGHT_SHIFT:
		return "OP_RIGHT_SHIFT";
	case TokenKind::OP_MODULO:
		return "OP_MODULO";
	case TokenKind::OP_PLUS_ASSIGN:
		return "OP_PLUS_ASSIGN";
	case TokenKind::OP_MINUS_ASSIGN:
		return "OP_MINUS_ASSIGN";
	case TokenKind::OP_MULTIPLY_ASSIGN:
		return "OP_MULTIPLY_ASSIGN";
	case TokenKind::OP_DIVIDE_ASSIGN:
		return "OP_DIVIDE_ASSIGN";
	case TokenKind::OP_MODULO_ASSIGN:
		return "OP_MODULO_ASSIGN";
	case TokenKind::PUNC_LPAREN:
		return "PUNC_LPAREN";
	case TokenKind::PUNC_RPAREN:
		return "PUNC_RPAREN";
	case TokenKind::PUNC_LBRACE:
		return "PUNC_LBRACE";
	case TokenKind::PUNC_RBRACE:
		return "PUNC_RBRACE";
	case TokenKind::PUNC_SEMICOLON:
		return "PUNC_SEMICOLON";
	case TokenKind::PUNC_DOT:
		return "PUNC_DOT";
	case TokenKind::PUNC_LBRACKET:
		return "PUNC_LBRACKET";
	case TokenKind::PUNC_RBRACKET:
		return "PUNC_RBRACKET";
	case TokenKind::PUNC_COLON:
		return "PUNC_COLON";
	case TokenKind::PUNC_COMMA:
		return "PUNC_COMMA";
	case TokenKind::PUNC_ARROW:
		return "PUNC_ARROW";
	case TokenKind::PUNC_RANGE:
		return "PUNC_RANGE";
	case TokenKind::PUNC_INCL_RANGE:
		return "PUNC_INCL_RANGE";
	case TokenKind::PUNC_INCL_BLK_COMMENT:
		return "PUNC_INCL_BLK_COMMENT";
	case TokenKind::PUNC_INCL_BLK_COMMENT_END:
		return "PUNC_INCL_BLK_COMMENT_END";
	case TokenKind::IDENTIFIER:
		return "IDENTIFIER";
	case TokenKind::LIT_STRING:
		return "LIT_STRING";
	case TokenKind::LIT_INT:
		return "LIT_INT";
	case TokenKind::LIT_FLOAT:
		return "LIT_FLOAT";
	case TokenKind::LIT_CHAR:
		return "LIT_CHAR";
	case TokenKind::LIT_TRUE:
		return "LIT_TRUE";
	case TokenKind::LIT_FALSE:
		return "LIT_FALSE";
	case TokenKind::INVALID_TOKEN:
		return "INVALID_TOKEN";
	case TokenKind::EOF_TOKEN:
		return "EOF_TOKEN";
	}
	return "UNKNOWN_TOKEN";
}
class DebugVisitor {
 public:
	void visit(const Token& token) {
		std::cout << token_kind_name(token.kind) << ", Location: [" << token.location.start
			  << ", " << token.location.length
			  << "], Text: " << std::string(token.text, token.location.length)
			  << std::endl;
	}
};
